################################################################
##                        Configuration                       ##
################################################################

Settings:
  # Specifies the required experience to level up.
  Required-Exp:
    # Specifies the default level up experience.
    Default: 5000
    # Specifies the custom level up experience. Usage of '*' before a level represents a repetitive pattern!
    Levels:
      '*0': 500
      '*1': 1000
      '*2': 2000
      '*3': 3500

  # Controls whether players can chat when they are not in a game.
  Player-Chat: true
  # Controls whether players take damage when they are not in a game.
  Player-Damage: false
  # Controls whether players can place blocks when they are not in a game.
  Player-Block-Placing: false
  # Controls whether players can destroy blocks when they are not in a game.
  Player-Block-Destroying: false
  # Controls whether players can interact with blocks when they are not in a game.
  Player-Block-Interact: false
  # Controls whether players can pick up items when they are not in a game.
  Player-Item-PickUp: false
  # Controls whether players can drop items when they are not in a game.
  Player-Item-Drop: false
  # Controls whether entities can pick up items or change blocks when they are not in a game.
  Entity-Griefing: false

  # Controls whether the lobby scoreboard should be applied to players when they are not in a game.
  Lobby-Scoreboard: true
  # Controls whether players should automatically reconnect back to their game after joining back the server.
  Auto-Reconnect: true
  # Controls whether the plugin should check for updates.
  Check-Updates: true

  # Specifies the default language to use for new users.
  Default-Language: English

Waiting-Room-Settings:
  # Time to wait before starting the game (in seconds).
  Countdown: 20

  # Required number of players to start the game. (Minimum: number of players possible in a team + 1)
  Minimum-Players:
    Solo: 7
    Doubles: 14
    3v3v3v3: 9
    4v4v4v4: 12

Game-Settings:
  # Specifies a custom preset of phases to use in games.
  #
  # Built-in game-phases: 'Diamond II', 'Diamond III', 'Emerald II', 'Emerald III', 'Bed Break', 'Sudden Death'
  Game-Phases:
    Default:
      - DIAMOND II
      - EMERALD II
      - DIAMOND III
      - EMERALD III
      - Bed Break
      - Sudden Death

  # Specifies the time to wait before respawning player. (In seconds)
  Game-Respawn:
    Default: 5
    Reconnect: 10

  # Specifies the time between the usage of the '/Shout' command. (In seconds)
  Game-Shouting-Time: 60

  # Specifies the play-time required by a player to receive the 'Time Played' reward. (In seconds)
  Game-Rewards-Time: 60

  # Controls the distribution of rewards to players in the game depending on a specific action.
  #
  # Built-in rewards: 'Bedwars-Experience, Bedwars-Coins'
  # Built-in actions: 'Bed-Destroyed, Time-Played, Final-Kil, Kill, Win'
  Game-Rewards:
    Bedwars-Experience:
      Time-Played: 25
      Win:
        Default: 100
        3v3v3v3: 50
        4v4v4v4: 50
    Bedwars-Coins:
      Bed-Destroyed: 20
      Time-Played: 10
      Win:
        Default: 100
        3v3v3v3: 50
        4v4v4v4: 50

  # Controls the behavior of different bedwars mechanisms.
  Game-Mechanics:
    Fireball:
      # Controls whether the fireball will bounce when a player interacts with it.
      Fireball-Bounce: false
      # Controls whether the explosion will cause fire.
      Explosion-Fire: false
      # The speed at which the fireball will travel by.
      Fireball-Speed: 1.5
      # The power of the explosion.
      Explosion-Power: 3.0
      # The damage of the explosion. (The further the player is, the less the damage is)
      Explosion-Damage: 4.0
    TNT:
      # Controls whether to display a text above the TNT indicating the time left to explode.
      Display-Explosion-Time: false
      # Controls whether the explosion will cause fire.
      Explosion-Fire: false
      # The time to wait before exploding in ticks. (1 second is 20 ticks)
      Explosion-Time: 60
      # The power of the explosion.
      Explosion-Power: 4.0
      # The damage of the explosion. (The further the player is, the less the damage is)
      Explosion-Damage: 4.0
    Bridge-Egg:
      # The block type of the bridge.
      Bridge-Block-Type: WHITE_WOOL
      # The maximum length of the bridge. (Between 5 and 30)
      Bridge-Length: 30
      # The maximum width of the bridge. (Between 1 and 3)
      Bridge-Width: 1
    Sponge:
      # The radius of the sponge effect. (Between 1 and 5)
      Particles-Radius: 5
      # The growth's rate of the sponge effect. (Between 1 and 4)
      Particles-Rate: 2

  # Controls some properties of custom bedwars mobs.
  #
  # Built-in entities: 'Body Guard', 'Bed Bug'
  Game-Entities:
    Body Guard:
      # The duration to wait before removing this mob. (In seconds)
      Duration: 240
      # The amount of damage this mob can deal.
      Damage: 7
      # The amount of health of this mob. (1HP is half a heart)
      Health: 20
      # The maximum number of entities a team can spawn. (-1 for unlimited)
      Limit: 2
    Bed Bug:
      Duration: 15
      Damage: 1
      Health: 8
      Limit: -1

# Controls the connection with the database. The placeholders <username>, <password> in the URL will be replaced by the provided username and password.
#
# Supported databases: MySQL
Database:
  # Controls whether the database is enabled or not.
  Enabled: false
  # Controls whether user data will be loaded and saved from/to the database.
  Userdata: false
  # The type of the database to use.
  Database-Type: MySQL
  # The username to use for authentication.
  Database-Username: root
  # The password to use for authentication.
  Database-Password: ""
  # The connection string for the database.
  Database-URL: jdbc:mysql://localhost:3306/bedwars
